gtnh.settings.blowdryerTag = 0.2.2

modName = AE2 Icon Exporter
modId = ae2iconexporter
modGroup = dev.fopwoc.ae2iconexporter
useModGroupForPublishing = true

autoUpdateBuildScript = false
minecraftVersion = 1.7.10
forgeVersion = 10.13.4.1614
channel = stable
mappingsVersion = 12
remoteMappings = https\://raw.githubusercontent.com/MinecraftForge/FML/1.7.10/conf/
developmentEnvironmentUserName = Developer

enableModernJavaSyntax = jabel
enableGenericInjection = true
generateGradleTokenClass = dev.fopwoc.ae2iconexporter.Tags
gradleTokenVersion = VERSION
replaceGradleTokenInFile =
apiPackage =
accessTransformersFile =

usesMixins = false
separateMixinSourceSet =
usesMixinDebug = false
mixinPlugin =
mixinsPackage =
coreModClass =
containsMixinsAndOrCoreModOnly = false
forceEnableMixins = false

usesShadowedDependencies = false
minimizeShadowedDependencies = true
relocateShadowedDependencies = true
includeWellKnownRepositories = true
excludeWellKnownRepositories =
usesMavenPublishing = false
modrinthProjectId =
modrinthRelations =
curseForgeProjectId =
curseForgeRelations =

org.gradle.configuration-cache = true
org.gradle.parallel = true
